name: visual-intelligence
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pytorch=2.5.1
  - pytorch-cuda=12.1
  - pip
  - pip:
    - absl-py==2.3.1
    - colorama==0.4.6
    - filelock==3.20.0
    - fsspec==2025.10.0
    - grpcio==1.76.0
    - importlib_resources==6.5.2
    - Jinja2==3.1.6
    - joblib==1.5.2
    - Markdown==3.10
    - MarkupSafe==3.0.3
    - monai==1.5.1
    - mpmath==1.3.0
    - networkx==3.5
    - nibabel==5.3.2
    - numpy==2.3.5
    - packaging==25.0
    - pandas==2.3.3
    - pillow==12.0.0
    - protobuf==6.33.1
    - python-dateutil==2.9.0.post0
    - pytz==2025.2
    - scikit-learn==1.7.2
    - scipy==1.16.3
    - six==1.17.0
    - sympy==1.14.0
    - tensorboard==2.20.0
    - tensorboard-data-server==0.7.2
    - threadpoolctl==3.6.0
    - tqdm==4.67.1
    - typing_extensions==4.15.0
    - tzdata==2025.2
    - Werkzeug==3.1.3
